---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
      useEmulation: true
    imagePullPolicy: IfNotPresent
  infra:
    nodePlacement:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - platform
      nodeSelector:
        workload: platform
      tolerations:
        - key: workload
          operator: Equal
          value: platform
          effect: NoSchedule
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloads:
    nodePlacement:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - vm
      nodeSelector:
        workload: vm
      tolerations:
        - key: workload
          operator: Equal
          value: vm
          effect: NoSchedule
  workloadUpdateStrategy: {}
